#mysql:
#  image: "mysql:5"
#  ports:
#    - "3307:3306"
#  environment:
#    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#    #MYSQL_ROOT_PASSWORD: "19871024"
postgres:
  image: "postgres:9.6"
  environment:
    POSTGRES_USER: "zenhack-api"
    POSTGRES_PASSWORD: "zenhack-koiki"
zenhack-api:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - ".:/usr/src/zenhack-api"
  command: "bundle exec rails server -b 0.0.0.0"
  links:
    - postgres
