# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc8f28a5df03d3f7e13f3a46edf3cfefab6a8a4a67d96531483468884f0bc9448140b1372f9f11f644b0e45072237fb99dae56e8f6f28d826df861099907dcd5

test:
  secret_key_base: 8883a16694ac7ce0034083425db165d0caee9416e7071da850bea369f1c1f2259a2bebcd0bdf791cfefd1ae84949fb34560a4879b0758dfc1ecfc4548c3c3836

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
